# Docker Compose File for fNIRS Web App

services:

  fnirsWebApp:
    build:
      context: .
      dockerfile: Dockerfile
    image: codeadeel/private:fnirswebapp
    container_name: fnirswebapp
    hostname: fnirswebapp
    expose:
      - 8080
    environment:
      - ALLOWED_USER=aeelab # Login : Username
      - ALLOWED_PASSWORD=aeelab # Login : Password
      - ALLOWED_AGE=43200000 # Security : JWT Expiry
      - PORT=8080 # Network : Express Port
    networks:
      - fnirsNetwork

networks:
  fnirsNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/16
