name: 'Google Cloud Run Deployment'

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  currentTime: date '+%Y-%m-%d_%H-%M-%S'

jobs:
  Cloud-Run-Deployment:
    runs-on: 'ubuntu-latest'

    steps:
      - name: main Branch Checkout
        uses: actions/checkout@v4
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2.1.4
        with:
          credentials_json: ${{secrets.GOOGLE_SERVICE_ACCOUNT}}
      
      - name: Setup gcloud Cloud SDK Environment
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Docker Authentication'
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      
      - name: Build Web Portal
        run: docker build -t ${{ vars.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ vars.ARTIFACT_REGISTRY }}/${{ vars.SERVICE_NAME }}:${{ env.currentTime }} .

      - name: Push Build Container
        run: docker push ${{ vars.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ vars.ARTIFACT_REGISTRY }}/${{ vars.SERVICE_NAME }}:${{ env.currentTime }}
      
      - name: Google Cloud Run Deploy
        uses: google-github-actions/deploy-cloudrun@v2.7.0
        with:
          service: ${{ vars.SERVICE_NAME }}
          region: ${{ vars.REGION }}
